### ISSUE TITLE
Erro hxCFFILoader - HAXE3

### ISSUE THREAD

**Issue by Espigah** [andyli/hxSerial#4]
Could not link plugin to process (hxCFFILoader.h 636)

**Comment by Espigah** [comment]
var serialObj:Serial = new hxSerial.Serial("COM2", 9600);
		trace(serialObj.isSetup);
		trace(serialObj.portName);
		trace(serialObj.setup());
		trace(serialObj.isSetup);
		trace(serialObj.baud);

**Comment by andyli** [comment]
Same as #6.
