### ISSUE TITLE
Could not compile to neko using openfl

### ISSUE THREAD

**Issue by alijaya** [andyli/hxSerial#7]
add `<haxelib name="hxSerial" />`

hxSerial.ndll doesn't found... Compile Error

add `<ndll name="hxSerial" haxelib="hxSerial" />`

Compile Success, but the runtime crashing...

**Comment by andyli** [comment]
What is the versions of haxe, hxcpp, and neko you're using?
Have you tried putting hxSerial.ndll next to the .n file?

**Comment by alijaya** [comment]
haxe 3.1.3
hxcpp 3.2.37
neko 2.0.0
openfl 3.0.0-beta.3

Yeah I have tried to put hxSerial.ndll next to the .n file in Export/mac64/neko/obj/, but no result...

**Comment by alijaya** [comment]
If I don't use openfl, just use normal hxml, it works wonderfully...

**Comment by andyli** [comment]
I can reproduce the issue on my mac.
The problem comes from the `libneko.dylib` file added by OpenFL. The program can be run without error as follows:
1. `haxelib run openfl build neko`
2. `rm Export/mac64/neko/bin/*.app/Contents/MacOS/libneko.dylib`
3. `haxelib run openfl run neko`

@hughsando Is the `libneko.dylib` thing no longer needed? Would any old ndll depends on it?

**Comment by hughsando** [comment]
Yes - if you are running a native-neko ndll with natve-neko build (eg hxSerial + openfl neko), then I think you do not need this file. I have pretty much deprecated the libneko wrapper in favour of building the wrapping code into the ndll itself via the "NEKO_COMPATIBLE".
You can use the technique to build a "universal" ndll file which will run in both hxcpp and neko applications by building with the hxcpp cffi system.
In fact, I have done this for this library:
https://github.com/hughsando/hxSerial
I have been meaning to give you  PR for this, but could not really test the linux binaries.

**Comment by andyli** [comment]
@hughsando In fact I've cherry-picked your commit into this repo. I roughly checked it works on win/mac/linux :)

@alijaya I've reported the issue to OpenFL (https://github.com/openfl/openfl/issues/579). You may subscribe and discuss there.

**Comment by alijaya** [comment]
Great thanks :D
